// Package docs — gerado pelo swaggo/swag (stub local para desenvolvimento).
// O arquivo definitivo é gerado automaticamente pelo Dockerfile via "swag init".
// Code generated by swaggo/swag. DO NOT EDIT.
package docs
